import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0b1326",
        "on-secondary": "#131e8c",
        "on-primary-container": "#00563b",
        "inverse-primary": "#006c4b",
        "on-secondary-container": "#a8afff",
        outline: "#85948b",
        "surface-container-highest": "#2d3449",
        "on-tertiary-fixed": "#2a1700",
        "secondary-fixed": "#e0e0ff",
        secondary: "#bdc2ff",
        primary: "#5af0b3",
        "on-primary-fixed": "#002114",
        "secondary-fixed-dim": "#bdc2ff",
        "tertiary-fixed": "#ffddb8",
        "on-primary-fixed-variant": "#005137",
        "surface-container": "#171f33",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#2f3aa3",
        "inverse-on-surface": "#283044",
        "secondary-container": "#2f3aa3",
        "on-surface": "#dae2fd",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dae2fd",
        "primary-fixed": "#68fcbf",
        "on-tertiary-container": "#6b4200",
        "primary-fixed-dim": "#45dfa4",
        "on-error": "#690005",
        "on-secondary-fixed": "#000767",
        "surface-container-low": "#131b2e",
        "on-background": "#dae2fd",
        "primary-container": "#34d399",
        "surface-bright": "#31394d",
        "surface-tint": "#45dfa4",
        "surface-variant": "#2d3449",
        "surface-container-high": "#222a3d",
        "on-tertiary": "#472a00",
        "on-primary": "#003825",
        "surface-dim": "#0b1326",
        "tertiary-fixed-dim": "#ffb95f",
        surface: "#0b1326",
        "surface-container-lowest": "#060e20",
        error: "#ffb4ab",
        "on-surface-variant": "#bbcac0",
        "on-tertiary-fixed-variant": "#653e00",
        "tertiary-container": "#ffa929",
        tertiary: "#ffcf96",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
      },
      spacing: {
        gutter: "1rem",
        "gutter-tablet": "1.5rem",
        margin: "1rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
