import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        "on-secondary": "var(--on-secondary)",
        "on-primary-container": "var(--on-primary-container)",
        "inverse-primary": "var(--inverse-primary)",
        "on-secondary-container": "var(--on-secondary-container)",
        outline: "var(--outline)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "secondary-fixed": "var(--secondary-fixed)",
        secondary: "var(--secondary)",
        primary: "var(--primary)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "surface-container": "var(--surface-container)",
        "error-container": "var(--error-container)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "secondary-container": "var(--secondary-container)",
        "on-surface": "var(--on-surface)",
        "on-error-container": "var(--on-error-container)",
        "inverse-surface": "var(--inverse-surface)",
        "primary-fixed": "var(--primary-fixed)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "on-error": "var(--on-error)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "surface-container-low": "var(--surface-container-low)",
        "on-background": "var(--on-background)",
        "primary-container": "var(--primary-container)",
        "surface-bright": "var(--surface-bright)",
        "surface-tint": "var(--surface-tint)",
        "surface-variant": "var(--surface-variant)",
        "surface-container-high": "var(--surface-container-high)",
        "on-tertiary": "var(--on-tertiary)",
        "on-primary": "var(--on-primary)",
        "surface-dim": "var(--surface-dim)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        surface: "var(--surface)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        error: "var(--error)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "tertiary-container": "var(--tertiary-container)",
        "journey-completed": "var(--journey-completed)",
        "journey-upcoming": "var(--journey-upcoming)",
        "journey-node-completed-bg": "var(--journey-node-completed-bg)",
        "journey-node-completed-text": "var(--journey-node-completed-text)",
        "journey-node-completed-border": "var(--journey-node-completed-border)",
        tertiary: "var(--tertiary)",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        mono: ["var(--font-inter)", "Inter", "sans-serif"],
        display: ["var(--font-playfair-display)", "Georgia", "serif"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
      },
      spacing: {
        gutter: "1rem",
        "gutter-tablet": "1.5rem",
        margin: "1rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
