import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#F8F5FB",
        "on-secondary": "#FFFFFF",
        "on-primary-container": "#42128A",
        "inverse-primary": "#6C00FF",
        "on-secondary-container": "#4D3270",
        outline: "#D9D1E2",
        "surface-container-highest": "#E7E0EC",
        "on-tertiary-fixed": "#4E2F12",
        "secondary-fixed": "#EFE7FA",
        secondary: "#7751A2",
        primary: "#6C00FF",
        "on-primary-fixed": "#260052",
        "secondary-fixed-dim": "#D8C8EF",
        "tertiary-fixed": "#F7E3CE",
        "on-primary-fixed-variant": "#4A2180",
        "surface-container": "#F5F0F8",
        "error-container": "#FCE8E6",
        "on-secondary-fixed-variant": "#493261",
        "inverse-on-surface": "#F8F5FB",
        "secondary-container": "#E9DDF7",
        "on-surface": "#24212A",
        "on-error-container": "#7F1D1D",
        "inverse-surface": "#302B35",
        "primary-fixed": "#EBDDFF",
        "on-tertiary-container": "#70451E",
        "primary-fixed-dim": "#D3B6FF",
        "on-error": "#FFFFFF",
        "on-secondary-fixed": "#2D183F",
        "surface-container-low": "#FBF9FD",
        "on-background": "#24212A",
        "primary-container": "#EBDDFF",
        "surface-bright": "#FFFFFF",
        "surface-tint": "#6C00FF",
        "surface-variant": "#ECE6F1",
        "surface-container-high": "#EEE8F3",
        "on-tertiary": "#FFFFFF",
        "on-primary": "#FFFFFF",
        "surface-dim": "#F1ECF5",
        "tertiary-fixed-dim": "#EBC9A6",
        surface: "#FFFDFF",
        "surface-container-lowest": "#FFFFFF",
        error: "#B3261E",
        "on-surface-variant": "#625B6B",
        "on-tertiary-fixed-variant": "#6B4525",
        "tertiary-container": "#F5E0CA",
        tertiary: "#A45B20",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        mono: ["var(--font-inter)", "Inter", "sans-serif"],
        display: ["var(--font-playfair-display)", "Georgia", "serif"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
      },
      spacing: {
        gutter: "1rem",
        "gutter-tablet": "1.5rem",
        margin: "1rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
